services:
  b2-app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      app-net:
        aliases:
          - "b2.blog.local"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.b2-blog.rule=Host(`b2.blog.local`)"
      - "traefik.http.routers.b2-blog-https.rule=Host(`b2.blog.local`)"
      - "traefik.http.routers.b2-blog-https.tls=true"

  b2-mysql:
    restart: unless-stopped
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=b2
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=b2
    volumes:
      - ./my.cnf:/etc/my.cnf
      - dbdata:/var/lib/mysql
    networks:
      app-net:
        aliases:
          - "b2-db.blog.local"

networks:
  app-net: ~

volumes:
  dbdata: ~
